minify: true
custom_file_path:
  header: source/_data/header.njk
  style: source/_data/styles.styl
  sidebar: source/_data/sidebar.njk
scheme: Muse
#darkmode: true
avatar: 
  url: https://img.njzjz.win/?url=https://api.njzjz.win/1UZOmNVE8C3GgIQEWpj7qmzCb5v63VXK5
favicon:
  small: https://img.njzjz.win/?url=https://api.njzjz.win/1UZOmNVE8C3GgIQEWpj7qmzCb5v63VXK5
  medium: https://img.njzjz.win/?url=https://api.njzjz.win/1UZOmNVE8C3GgIQEWpj7qmzCb5v63VXK5
  apple_touch_icon: https://img.njzjz.win/?url=https://api.njzjz.win/1UZOmNVE8C3GgIQEWpj7qmzCb5v63VXK5
  safari_pinned_tab: https://img.njzjz.win/?url=https://api.njzjz.win/1UZOmNVE8C3GgIQEWpj7qmzCb5v63VXK5
menu:
  HOME: / 
  TEAM: /people/ 
  RESEARCH: /research/
  PUBLICATIONS: /publications/
  SOFTWARES: /softwares/
  TEACHING: /teaching/
  MEMORY: /memory/
  "GROUP SEMINAR": /group-seminar/
  TIPS: /tips/
sidebar:
  position: right
  display: hide
site_state: false
toc:
  enable: false
preconnect: true
exturl: true
mediumzoom: true
lazyload: true
pangu: false
vendors:
  internal: jsdelivr
  plugins: jsdelivr
font:
  enable: true
  global:
    family: Open Sans
    size: 0.6875
  title:
    size: 1.625
footer:
  powered: false
index_with_subtitle: true
motion:
  enable: false